  - name: install and run nginx
    hosts: web
    become: yes # -b
    tasks:
    - name: install nginx 
      ansible.builtin.package:
        name: nginx
        state: presant # current the typo here
    - name: start the nginx
      ansible.builtin.service:
       name: nginx
       state: started    