- name: variable from files
  hosts: local
  connection: local 
  vars-files: 
  - variable.yaml # correct indentation for vars_files
  tasks:
  - name: print variable information
    ansible.builtin.debug:
      msg: "course is {{ COURSE}}, Duration is {{ DURATION}}, Trainer is {{ TRAINER}}"