- name: variable from files
  hosts: local
  connection: local 
  vars_files: 
  - variable.yaml # Reference the variable file here
  tasks:
  - name: print variable information
    ansible.builtin.debug:
      msg: "course is {{ COURSE}}, Duration is {{ DURATION}}, Trainer is {{ TRAINER}}"