  - name: filters
    hosts: local
    connection: local
    tasks:
    - name: hamdle undefine variable
      ansible.builtin.debug:
        msg: "HELLO {{ person | default('kavya') }}" 

    - name: convert string to list
      vars:
        Fruits: "apple, orange"  #string
      ansible.builtin.debug:
        msg: "Fruits are: {{ Fruits | split(',')}}"    

    - name: convert map into list
      vars: 
        course:
           name: ansible
           duration: 10hrs
           trainer: kavya
      ansible.builtin.debug: 
        msg: "course info: {{ course | dict2items }}" 


    - name: convert list into map   
      vars:
        course:
        - {'key': 'name', 'value': 'ansible'}
        - {'key': 'duration', 'value': '10hrs'}
        - {'key': 'trainer', 'value': 'kavya'}
      ansible.builtin.debug:
        msg: "course info: {{ course | items2dict }}"

    - name: convert upper to lower
      vars:
       name: "KAVYA reddy K"
      ansible.builtin.debug:
        msg: "HELLO {{ name | lower }}" 
  
    - name: convert lower to upper
      vars:
       name: "KAVYA reddy K"
      ansible.builtin.debug:
        msg: "HELLO {{ name | upper }}" 

    - name: print min and max
      vars:
        numbers: [1,30,38,36,87,8888,999,000,643679,]
      ansible.builtin.debug:
        msg: "Min is: {{ numbers | min }} max is: {{ numbers | max }}"      

    - name: check ipaddress is vaid or not
      vars:
        ip: "172.31.83.125"
      ansible.builtin.debug:
        msg: "{{ ip | ansible.utils.ipaddr }}"  
      